strategies:
  - model: openrouter/anthropic/claude-3.5-sonnet
    prompt_name: correct_cn_audio_transcription
    input_format: |
      original text:
      {{text}}
      vocabulary:
      {{vocab}}
    output_name: correction
  - model: openrouter/01-ai/yi-large
    prompt_name: comment_cn_audio_transcription
    input_format: |
      original text:
      {{text}}
      correction:
      {{correction}}
    output_name: reflection
  - model: openrouter/qwen/qwen-2-72b-instruct
    prompt_name: improve_transcription_wsy_cn
    input_format: |
      original text:
      {{text}}
      correction:
      {{correction}}
      comments:
      {{reflection}}
    output_name: improvement